### PR TITLE
added a responsive navigation bar

### PR DESCRIPTION
**Pull request by srinjoy-26**
made required changes.
Please review.
done #4 
Screenshot 2022-06-05 220035
Screenshot 2022-06-05 220103

### CODE REVIEW

**Comment by srinjoy-26** [comment]
@Tess314 , @Mohasin-Haque please merge if no issues are there

**Comment by Mohasin-Haque** [comment]
>Please be patience team is reviewing the code. You will get the updates soon.

**Comment by isomoth** [comment]
Good job! I like how fluid the responsiveness looks. And the hamburger menu is looking good, too. Since this is a summer-themed website, have you considered a more lively color theme? Other than that, it's great.

**Comment by srinjoy-26** [comment]
> Good job! I like how fluid the responsiveness looks. And the hamburger menu is looking good, too. Since this is a summer-themed website, have you considered a more lively color theme? Other than that, it's great.

no actually the navbar would look good in black , please merge

**Comment by Tess314** [comment]
@srinjoy-26 Please ensure your code files are stored within a folder as shown below, and we shall then merge your pull request👍
image

**Pull request closed without merging**
